services:
  navbatchilik-bot:
    build: .
    container_name: navbatchilik-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Tashkent
      DATA_DIR: /app/data
    volumes:
      - ./data:/app/data
